@extends('layouts.index')

@section('content')
<div class="container mt-2 mb-5">

    <div class="row pt-3 pb-3 justify-content-center">
        <img src="{{asset('images/logo.png')}}"  width="240px" height="170px" alt="">
    </div>

    <div class="card">
        <div class="card-body">
            <div class="row">

                <div class="col-md-6">

                    <h3 class="mt-3 mb-2">Quick register</h3>
                    <div class="separator"></div>

                    <p class="mt-3">Create a homework pro writers account easily using your email only</p>

                    <form action="{{route('quick_register')}}" method="post">
                        @csrf
                        <div class="form-group">
                            <label for="" class="text-success">Email address:</label>
                            <input type="email"  placeholder="customer@email.com" name="customer_email" class="form-control">
                            <span class="text-danger">{{($errors->has('customer_email')?$errors->first('customer_email'):"")}}</span>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Create your account</button>
                        </div>
                    </form>

                    <p class="font-weight-bold text-info mt-3">
                        <i class="fa fa-info-circle"></i> An email with your autogenerated password will be sent to this email address. You can update your name and password later under your profile information
                    </p>


                </div>
                <div class="col-md-6 border-left">

                    <h3 class="mt-3 mb-2">Log in</h3>
                    <div class="separator"></div>
                    <p class="pt-3 pb-3">Already have an account? use your credentials to login</p>

                    <form class="mt-3" method="POST" action="{{ route('login') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required autofocus>

                                @if ($errors->has('email'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-6 offset-md-4">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="remember" id="remember" {{ old('remember') ? 'checked' : '' }}>

                                    <label class="form-check-label" for="remember">
                                        {{ __('Remember Me') }}
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Login') }}
                                </button>

                                @if (Route::has('password.request'))
                                    <a class="btn btn-link" href="{{ route('password.request') }}">
                                        {{ __('Forgot Your Password?') }}
                                    </a>
                                @endif
                            </div>
                        </div>
                    </form>

                </div>

            </div>
        </div>
    </div>
</div>
@endsection
